#!/usr/bin/env bash
# =============================================================================
# 02-install-ubuntu.sh
# =============================================================================
# This script:
#   1. Installs Ubuntu base system via debootstrap
#   2. Generates fstab and crypttab
#   3. Sets up chroot environment
#   4. Installs kernel, firmware, and essential packages inside chroot
#   5. Configures locale, timezone, hostname, networking
#   6. Creates a user account
#
# Prerequisites:
#   - Script 01 has been run successfully
#   - All partitions are mounted at /mnt
#   - You have an internet connection
#
# Usage:
#   sudo bash 02-install-ubuntu.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/00-config.sh"

require_root

# ─── Verify mounts ──────────────────────────────────────────────────────────

step "Verifying mount layout"

if ! mountpoint -q "$TARGET"; then
    echo "ERROR: $TARGET is not mounted. Did you run 01-partition-and-encrypt.sh?"
    exit 1
fi

if ! mountpoint -q "$TARGET/boot/efi"; then
    echo "ERROR: $TARGET/boot/efi is not mounted."
    exit 1
fi

echo "Mount layout looks good:"
findmnt --target "$TARGET" --real
echo ""

# ─── Step 1: Install debootstrap if needed ───────────────────────────────────

step "Ensuring debootstrap is available"

if ! command -v debootstrap &>/dev/null; then
    echo "Installing debootstrap..."
    apt-get update
    apt-get install -y debootstrap
fi

echo "debootstrap is available."

# ─── Step 2: Bootstrap Ubuntu ────────────────────────────────────────────────

step "Bootstrapping Ubuntu $UBUNTU_RELEASE into $TARGET"

echo "This will download and install the base Ubuntu system."
echo "It requires an internet connection and may take a while."
echo ""

if [[ -f "$TARGET/usr/bin/apt-get" ]]; then
    echo "debootstrap appears to have already run (found apt-get in target). Skipping."
else
    debootstrap --arch=amd64 "$UBUNTU_RELEASE" "$TARGET" "$UBUNTU_MIRROR" || {
        echo ""
        echo "ERROR: debootstrap failed."
        echo "Check the log for details: $TARGET/debootstrap/debootstrap.log"
        if [[ -f "$TARGET/debootstrap/debootstrap.log" ]]; then
            echo ""
            echo "Last 20 lines of debootstrap.log:"
            tail -20 "$TARGET/debootstrap/debootstrap.log"
        fi
        exit 1
    }
    echo "Base system installed."
fi

# ─── Step 3: Generate fstab ─────────────────────────────────────────────────

step "Generating /etc/fstab"

# Get UUIDs — validate non-empty: blkid returns "" with exit 0 if formatting failed
EFI_UUID=$(blkid -s UUID -o value "$EFI_PART")
if [[ -z "$EFI_UUID" ]]; then
    echo "ERROR: Could not read UUID from $EFI_PART. Was mkfs.fat run successfully in script 01?"
    exit 1
fi
ROOT_BTRFS_UUID=$(blkid -s UUID -o value /dev/mapper/"$ROOT_MAPPER")
if [[ -z "$ROOT_BTRFS_UUID" ]]; then
    echo "ERROR: Could not read UUID from /dev/mapper/$ROOT_MAPPER. Was mkfs.btrfs run successfully?"
    exit 1
fi

cat > "$TARGET/etc/fstab" << EOF
# /etc/fstab — generated by install script
# <filesystem>                           <mount>           <type>  <options>                                    <dump> <pass>

# EFI System Partition
UUID=$EFI_UUID                           /boot/efi         vfat    defaults                                     0      1

# Btrfs subvolumes on encrypted root
UUID=$ROOT_BTRFS_UUID                    /                 btrfs   subvol=$SUBVOL_ROOT,$BTRFS_OPTS              0      0
UUID=$ROOT_BTRFS_UUID                    /home             btrfs   subvol=$SUBVOL_HOME,$BTRFS_OPTS              0      0
UUID=$ROOT_BTRFS_UUID                    /var/log          btrfs   subvol=$SUBVOL_LOG,$BTRFS_OPTS               0      0
UUID=$ROOT_BTRFS_UUID                    /var/cache/apt    btrfs   subvol=$SUBVOL_PKG,$BTRFS_OPTS               0      0

# Swap subvolume — deliberately omits compress=zstd from BTRFS_OPTS.
# Btrfs refuses to activate a swapfile on a compressed extent (swapon fails
# with EINVAL). noatime is kept to reduce unnecessary metadata writes.
UUID=$ROOT_BTRFS_UUID                    /swap             btrfs   subvol=$SUBVOL_SWAP,noatime                  0      0

# NOTE: The Incus disk (/dev/mapper/$INCUS_MAPPER) is NOT mounted here.
# Incus will manage it directly as a storage pool.
# However, we still need it in crypttab so it gets unlocked at boot.
EOF

echo "Generated /etc/fstab:"
cat "$TARGET/etc/fstab"

# ─── Step 4: Generate crypttab ──────────────────────────────────────────────

step "Generating /etc/crypttab"

ROOT_PART_UUID=$(blkid -s UUID -o value "$ROOT_PART")
if [[ -z "$ROOT_PART_UUID" ]]; then
    echo "ERROR: Could not read UUID from $ROOT_PART. Was the partition created successfully?"
    exit 1
fi
INCUS_PART_UUID=$(blkid -s UUID -o value "$INCUS_PART")
if [[ -z "$INCUS_PART_UUID" ]]; then
    echo "ERROR: Could not read UUID from $INCUS_PART. Was the partition created successfully?"
    exit 1
fi

cat > "$TARGET/etc/crypttab" << EOF
# /etc/crypttab — generated by install script
# <target>       <source device>                          <key file>       <options>
$ROOT_MAPPER     UUID=$ROOT_PART_UUID                     none             luks,discard
$INCUS_MAPPER    UUID=$INCUS_PART_UUID                    none             luks,discard
EOF

echo "Generated /etc/crypttab:"
cat "$TARGET/etc/crypttab"
echo ""
echo "NOTE: The Incus disk will ask for a second password at boot."
echo "      Script 03 will set up a keyfile to avoid this."

# ─── Step 5: Configure APT sources ──────────────────────────────────────────

step "Configuring APT sources"

cat > "$TARGET/etc/apt/sources.list" << EOF
deb $UBUNTU_MIRROR $UBUNTU_RELEASE main restricted universe multiverse
deb $UBUNTU_MIRROR ${UBUNTU_RELEASE}-updates main restricted universe multiverse
deb $UBUNTU_MIRROR ${UBUNTU_RELEASE}-security main restricted universe multiverse
deb $UBUNTU_MIRROR ${UBUNTU_RELEASE}-backports main restricted universe multiverse
EOF

echo "APT sources configured."

# ─── Step 6: Set up chroot environment ───────────────────────────────────────

step "Setting up chroot bind mounts"

mountpoint -q "$TARGET/dev"     || mount --bind /dev     "$TARGET/dev"
mountpoint -q "$TARGET/dev/pts" || mount --bind /dev/pts "$TARGET/dev/pts"
mountpoint -q "$TARGET/proc"    || mount --bind /proc    "$TARGET/proc"
mountpoint -q "$TARGET/sys"     || mount --bind /sys     "$TARGET/sys"
mountpoint -q "$TARGET/run"     || mount --bind /run     "$TARGET/run"

# Copy DNS resolution into chroot.
# On Ubuntu live USBs, /etc/resolv.conf is a symlink whose target may not exist.
# Fall back to a static resolver if the copy fails.
if [[ -f /etc/resolv.conf ]]; then
    # Remove any symlink in the target first. On live Ubuntu, /etc/resolv.conf
    # is a symlink into /run/systemd/resolve/; since /run is bind-mounted into
    # the chroot, a plain cp sees source and destination as the same file.
    rm -f "$TARGET/etc/resolv.conf"
    cp /etc/resolv.conf "$TARGET/etc/resolv.conf"
else
    echo "WARNING: /etc/resolv.conf not found on live system. Writing fallback nameserver."
    echo "nameserver 1.1.1.1" > "$TARGET/etc/resolv.conf"
fi

echo "Chroot environment ready."

# ─── Step 7: Install packages inside chroot ──────────────────────────────────

step "Installing kernel, firmware, and essential packages"

chroot "$TARGET" /bin/bash -e << 'CHROOT_EOF'

# Update package lists
apt-get update

# Install essential packages.
# - linux-oem-6.14: complete OEM kernel + headers — broader hardware support
#   than linux-image-generic; tracks the latest 6.14.x OEM kernel
# - linux-firmware: hardware firmware blobs
# - initramfs-tools: builds the initramfs
# - cryptsetup: LUKS tools
# - cryptsetup-initramfs: CRITICAL — adds LUKS support to the initramfs
#   Without this, the initramfs will NOT prompt for your LUKS password!
# - btrfs-progs: Btrfs management tools
# - efibootmgr: manages UEFI boot entries
# - dosfstools: FAT32 tools (for EFI partition)
# - git: needed to download Limine
# - sudo: so your user can run admin commands
# - systemd-timesyncd: NTP time sync
# - ubuntu-drivers-common: ubuntu-drivers autoinstall for proprietary drivers
# - network-manager: desktop-friendly network management
# - locales: locale support
# - console-setup: console font/keyboard
# - software-properties-common: add-apt-repository support

DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    linux-oem-6.14 \
    linux-firmware \
    initramfs-tools \
    cryptsetup \
    cryptsetup-initramfs \
    btrfs-progs \
    efibootmgr \
    dosfstools \
    git \
    sudo \
    systemd-timesyncd \
    ubuntu-drivers-common \
    pciutils \
    network-manager \
    locales \
    console-setup \
    software-properties-common \
    vim \
    wget \
    curl \
    ca-certificates

echo "Essential packages installed."

CHROOT_EOF

# ─── Step 8: Configure locale, timezone, hostname ───────────────────────────

step "Configuring locale, timezone, and hostname"

chroot "$TARGET" /bin/bash -e << CHROOT_EOF

# Generate locale
sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
update-locale LANG=en_US.UTF-8

# Set timezone. Default is UTC. Change TIMEZONE in 00-config.sh.
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

# Set hostname
echo "$HOSTNAME" > /etc/hostname
cat > /etc/hosts << EOF
127.0.0.1   localhost
127.0.1.1   $HOSTNAME

::1         localhost ip6-localhost ip6-loopback
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
EOF

echo "Locale, timezone, and hostname configured."

CHROOT_EOF

# ─── Step 9: Configure wired networking ──────────────────────────────────────

step "Configuring wired ethernet (NetworkManager)"

mkdir -p "$TARGET/etc/NetworkManager/system-connections"
cat > "$TARGET/etc/NetworkManager/system-connections/wired.nmconnection" << 'EOF'
[connection]
id=wired
type=ethernet
autoconnect=true

[ipv4]
method=auto

[ipv6]
method=auto
addr-gen-mode=stable-privacy
EOF

chmod 600 "$TARGET/etc/NetworkManager/system-connections/wired.nmconnection"

echo "Wired ethernet connection profile created."

# ─── Step 10: Create user account ────────────────────────────────────────────

step "Creating user account"

echo "Enter the username you want to create:"
read -rp "Username: " NEW_USER

# Validate username before use in an unquoted heredoc.
# Shell metacharacters or an empty string would cause useradd to receive corrupt arguments.
if [[ -z "$NEW_USER" ]] || [[ ! "$NEW_USER" =~ ^[a-z_][a-z0-9_-]*$ ]]; then
    echo "ERROR: Invalid username '$NEW_USER'."
    echo "       Must start with a lowercase letter or underscore, contain only [a-z0-9_-]."
    exit 1
fi

if grep -q "^$NEW_USER:" "$TARGET/etc/passwd" 2>/dev/null; then
    echo "User '$NEW_USER' already exists in the target system. Skipping user creation."
    echo "If you need to reset the password, run: chroot $TARGET passwd $NEW_USER"
else
    # Create user with home directory, add to important groups
    chroot "$TARGET" useradd -m -s /bin/bash -G sudo,adm,video,render "$NEW_USER"

    # passwd must run with the terminal as stdin, not a heredoc — otherwise
    # it cannot read the password interactively and fails with "do not match".
    echo "Set password for $NEW_USER:"
    chroot "$TARGET" passwd "$NEW_USER"

    # Verify the user account was actually created
    if [[ ! -d "$TARGET/home/$NEW_USER" ]]; then
        echo "ERROR: User home directory $TARGET/home/$NEW_USER was not created."
        echo "       useradd may have failed inside the chroot."
        exit 1
    fi
fi

echo ""
echo "============================================"
echo "  BASE SYSTEM INSTALLATION COMPLETE"
echo "============================================"
echo ""
echo "User '$NEW_USER' created and added to sudo group."
echo ""
echo "Next step: Run 03-configure-system.sh"
echo ""
